name: CI Pipeline

# Trigger workflow on push or pull request to any branch
on:
  push:
    branches: [ '*' ]        # All branches
  pull_request:
    branches: [ '*' ]        # PRs to any branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'   # Use your project Python version

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint pytest

      # Step 4: Run Pylint for code quality
      - name: Run Pylint
        run: |
          pylint **/*.py

      # Step 5: Run pytest for all tests
      - name: Run Tests
        run: |
          pytest tests/ --maxfail=1 --disable-warnings -q
